# Generated by Django 5.2.6 on 2025-10-05 18:57

import django.db.models.deletion
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=rrhh.models.upload_document_path),
        ),
        migrations.AlterField(
            model_name='documento',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fechasubida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='iddocumento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='idempleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='idtipodocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='idusuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='mimearchivo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombrearchivo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='documento',
            name='updatedat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
