# Generated by Django 5.2.6 on 2025-10-05 18:58

import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_documento_archivo_alter_documento_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=1024, upload_to=rrhh.models.upload_document_path),
        ),
    ]
