# Generated by Django 5.2.6 on 2025-10-05 19:01

import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=rrhh.models.upload_document_path),
        ),
    ]
