# Generated by Django 5.2.6 on 2025-10-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='estudiosuniversitarios',
            field=models.CharField(blank=True, db_column='estudiosUniversitarios', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefonocelular',
            field=models.CharField(blank=True, db_column='telefonoCelular', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefonoemergencia',
            field=models.CharField(blank=True, db_column='telefonoEmergencia', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefonoresidencial',
            field=models.CharField(blank=True, db_column='telefonoResidencial', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='titulonivelmedio',
            field=models.CharField(blank=True, db_column='tituloNivelMedio', max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='Empleado',
        ),
    ]
