# Generated by Django 5.2.6 on 2025-10-09 14:14

import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_remove_empleado_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=255, null=True, upload_to=rrhh.models.upload_document_path),
        ),
    ]
