# Generated by Django 5.2.6 on 2025-10-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='idcoordinador',
            field=models.IntegerField(db_column='idCoordinador', null=True),
        ),
    ]
