# Generated by Django 5.2.6 on 2025-10-09 23:03

from django.db import migrations
from rrhh.equipos_default import crear_equipos_por_defecto, eliminar_equipos_por_defecto


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_equipo_idcoordinador'),
    ]

    operations = [
        migrations.RunPython(crear_equipos_por_defecto, eliminar_equipos_por_defecto),
    ]
