# Generated by Django 5.2.6 on 2025-10-09 23:28

from django.db import migrations
from rrhh.roles_default import crear_roles_por_defecto, eliminar_roles_por_defecto


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_auto_20251009_1703'),
    ]

    operations = [
        migrations.RunPython(crear_roles_por_defecto, eliminar_roles_por_defecto),
    ]
