# Generated by Django 5.2.6 on 2025-10-11 23:46

from django.db import migrations

def crear_puestos_iniciales(apps, schema_editor):
    Puesto = apps.get_model('rrhh', 'Puesto')
    puestos_iniciales = [
        'Acompañante',
        'Coordinación operativa',
        'Coordinación de sub-programa',
        'Coordinación de programa',
        'Secretaría',
        'Conserjería',
        'Contador auxiliar',
        'Contadora general',
    ]
    for nombre in puestos_iniciales:
        Puesto.objects.create(
            nombrepuesto=nombre,
            descripcion=f'Puesto de {nombre.lower()}',
            salariobase=0,
            estado=True,
            idusuario=1  # puedes cambiar esto según tu lógica
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_auto_20251009_1728'),
    ]

    operations = [
        migrations.RunPython(crear_puestos_iniciales),
    ]
