# Generated by Django 5.2.6 on 2025-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_auto_20251011_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='inicioLaboral',
            field=models.DateTimeField(auto_now_add=True, db_column='inicioLaboral', null=True),
        ),
    ]
