# Generated by Django 5.2.6 on 2025-10-23 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_empleado_iniciolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='idpuesto',
            field=models.ForeignKey(blank=True, db_column='idPuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.puesto'),
        ),
    ]
