# Generated by Django 5.2.6 on 2025-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_empleado_idpuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='nombreconvocatoria',
            field=models.CharField(db_column='nombreConvocatoria', max_length=500),
        ),
    ]
