# Generated by Django 5.2.6 on 2025-10-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_alter_convocatoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
