# Generated by Django 5.2.6 on 2025-10-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_alter_convocatoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={},
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='idaspirante',
            field=models.ForeignKey(db_column='idAspirante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='rrhh.aspirante'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='idconvocatoria',
            field=models.ForeignKey(db_column='idConvocatoria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='rrhh.convocatoria'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('idaspirante', 'idconvocatoria')},
        ),
        migrations.AlterModelTable(
            name='postulacion',
            table='Postulacion',
        ),
    ]
