# Generated by Django 5.2.6 on 2025-10-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_alter_postulacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='idaspirante',
            field=models.ForeignKey(blank=True, db_column='idAspirante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.aspirante'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='idconvocatoria',
            field=models.ForeignKey(blank=True, db_column='idConvocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.convocatoria'),
        ),
        migrations.AlterModelTable(
            name='postulacion',
            table='postulacion',
        ),
    ]
