# Generated by Django 5.2.6 on 2025-10-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0015_alter_postulacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='idaspirante',
            field=models.ForeignKey(blank=True, db_column='idAspirante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.aspirante'),
        ),
    ]
