# Generated by Django 5.2.6 on 2025-10-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_documento_idaspirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='dpi',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AddConstraint(
            model_name='aspirante',
            constraint=models.UniqueConstraint(fields=('dpi',), name='unique_dpi'),
        ),
    ]
