# Generated by Django 5.2.6 on 2025-10-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0017_alter_aspirante_dpi_alter_empleado_dpi_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aspirante',
            name='unique_dpi',
        ),
    ]
