# Generated by Django 5.2.6 on 2025-10-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_ausencia_diagnostico'),
        ('rrhh', '0018_remove_aspirante_unique_dpi'),
    ]

    operations = [
    ]
