# Generated by Django 5.2.6 on 2025-10-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0019_merge_20251026_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadocapacitacion',
            name='iddocumento',
            field=models.ForeignKey(blank=True, db_column='idDocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.documento'),
        ),
    ]
