# Generated by Django 5.2.6 on 2025-10-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0020_empleadocapacitacion_iddocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadocapacitacion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
