# Generated by Django 5.2.6 on 2025-10-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_remove_empleadocapacitacion_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocapacitacion',
            name='fechaenvio',
            field=models.DateField(blank=True, db_column='fechaEnvio', null=True),
        ),
    ]
