# Generated by Django 5.2.6 on 2025-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0022_alter_empleadocapacitacion_fechaenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencia',
            name='motivo',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='cantidad_dias',
            field=models.IntegerField(blank=True, db_column='cantidadDias', null=True),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='es_iggs',
            field=models.BooleanField(db_column='esIGSS', default=False),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='otro',
            field=models.CharField(blank=True, db_column='otro', max_length=100, null=True),
        ),
    ]
