# Generated by Django 5.2.6 on 2025-11-01 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_remove_ausencia_motivo_ausencia_cantidad_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('idcriterio', models.AutoField(db_column='idCriterio', primary_key=True, serialize=False)),
                ('nombrecriterio', models.CharField(db_column='nombreCriterio', max_length=100)),
                ('descripcioncriterio', models.CharField(db_column='descripcionCriterio', max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'criterio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoevaluacion',
            fields=[
                ('idtipoevaluacion', models.AutoField(db_column='idTipoEvaluacion', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_column='nombreTipo', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'tipoevaluacion',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='evaluacioncriterio',
            name='idcriterioevaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tipoevaluacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='modalidad',
            field=models.CharField(blank=True, db_column='modalidad', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncriterio',
            name='observacion',
            field=models.CharField(blank=True, db_column='observacion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='observacion',
            field=models.CharField(db_column='observacion', max_length=150),
        ),
        migrations.AddField(
            model_name='evaluacioncriterio',
            name='idcriterio',
            field=models.ForeignKey(blank=True, db_column='idCriterio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.criterio'),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idseguimiento', models.AutoField(db_column='idSeguimiento', primary_key=True, serialize=False)),
                ('idresponsable', models.IntegerField(db_column='idResponsable')),
                ('fechaproximarev', models.DateTimeField(db_column='fechaProximaRev')),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idevaluacion', models.ForeignKey(blank=True, db_column='idEvaluacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.evaluacion')),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('idvariable', models.AutoField(db_column='idVariable', primary_key=True, serialize=False)),
                ('nombrevariable', models.CharField(db_column='nombreVariable', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idtipoevaluacion', models.ForeignKey(blank=True, db_column='idTipoEvaluacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.tipoevaluacion')),
            ],
            options={
                'db_table': 'variable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimientovariable',
            fields=[
                ('idseguimientovariable', models.AutoField(db_column='idSeguimientoVariable', primary_key=True, serialize=False)),
                ('accionmejora', models.TextField(db_column='accionMejora')),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idseguimiento', models.ForeignKey(blank=True, db_column='idSeguimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.seguimiento')),
                ('idvariable', models.ForeignKey(blank=True, db_column='idVariable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.variable')),
            ],
            options={
                'db_table': 'seguimientovariable',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='criterio',
            name='idvariable',
            field=models.ForeignKey(blank=True, db_column='idVariable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.variable'),
        ),
        migrations.DeleteModel(
            name='Criterioevaluacion',
        ),
    ]
