# Generated by Django 5.2.6 on 2025-11-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_criterio_tipoevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.estado'),
        ),
    ]
