# Generated by Django 5.2.6 on 2025-11-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0025_aspirante_idestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='estado',
            name='idusuario',
            field=models.IntegerField(db_column='idUsuario', default=1),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombreestado',
            field=models.CharField(db_column='nombreEstado', max_length=250),
        ),
    ]
