# Generated by Django 5.2.6 on 2025-11-06

from django.db import migrations

def create_default_estados(apps, schema_editor):
    Estado = apps.get_model('rrhh', 'Estado')

    # Estados para aspirantes
    estados_aspirantes = [
        {
            "nombreestado": "Postulado",
            "descripcion": "Aspirante ha postulado",
        },
        {
            "nombreestado": "Seleccionado para Entrevista",
            "descripcion": "Aspirante seleccionado para entrevista",
        },
        {
            "nombreestado": "Rechazado",
            "descripcion": "Aspirante no continúa en el proceso",
        },
    ]

    # Estados para convocatorias
    estados_convocatorias = [
        {
            "nombreestado": "Abierta",
            "descripcion": "Convocatoria disponible para postulaciones activas.",
        },
        {
            "nombreestado": "Cerrada",
            "descripcion": "Convocatoria cerrada. No se aceptan nuevas postulaciones.",
        },
        {
            "nombreestado": "Finalizada",
            "descripcion": "Convocatoria finalizada. Se completó el proceso de selección.",
        },
    ]

    # Unimos todas las listas
    todos_los_estados = estados_aspirantes + estados_convocatorias

    # Crear si no existen
    for e in todos_los_estados:
        if not Estado.objects.filter(nombreestado=e["nombreestado"]).exists():
            Estado.objects.create(
                nombreestado=e["nombreestado"],
                descripcion=e["descripcion"],
                estado=True,
                idusuario=1  # Puedes cambiar este valor si tu app usa otro usuario por defecto
            )

class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0026_alter_estado_descripcion_alter_estado_idusuario_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_estados),
    ]
