# Generated by Django 5.2.6 on 2025-11-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0027_create_default_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='idestado',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.estado'),
        ),
    ]
