# Generated by Django 5.2.6 on 2025-11-02 22:45

from django.db import migrations

def agregar_criterios_entrevista(apps, schema_editor):
    Tipoevaluacion = apps.get_model('rrhh', 'Tipoevaluacion')
    Variable = apps.get_model('rrhh', 'Variable')
    Criterio = apps.get_model('rrhh', 'Criterio')

    # Obtener tipo de evaluación "Entrevista"
    tipo, _ = Tipoevaluacion.objects.get_or_create(
        idtipoevaluacion=4,
        defaults={"nombretipo": "Entrevista", "estado": True, "idusuario": 1}
    )

    # Crear variable asociada
    variable, _ = Variable.objects.get_or_create(
        idtipoevaluacion=tipo,
        nombrevariable="Evaluación de Entrevista",
        defaults={"estado": True, "idusuario": 1}
    )

    criterios = [
        ("Experiencia laboral en el ámbito del puesto", "Años y tipo de experiencia en funciones similares; vinculación con organizaciones sociales o comunitarias."),
        ("Formación académica y técnica", "Nivel de estudios, especialización o formación complementaria relacionada con el cargo y los enfoques institucionales."),
        ("Conocimiento y práctica en enfoque de género", "Manejo de conceptos, metodologías y estrategias de equidad de género; capacidad para aplicarlos en contextos rurales o comunitarios."),
        ("Discurso incluyente y compromiso con la igualdad", "Su discurso y actitudes reflejan respeto, apertura, lenguaje inclusivo y promoción de la equidad."),
        ("Experiencia en promover alianzas o trabajo coordinado con otras instituciones", "Participación o promoción en redes, espacios interinstitucionales o alianzas estratégicas."),
        ("Habilidad para trabajar en equipos diversos", "Capacidad para integrarse, cooperar, respetar diferencias culturales, generacionales, de género y resolución pacífica de conflictos."),
        ("Competencias técnicas específicas", "Dominio de herramientas, metodologías o áreas propias del cargo (planificación, incidencia, educación popular, etc.)."),
        ("Conocimiento del contexto social y político", "Comprensión de las realidades rurales, indígenas, de mujeres y juventudes, así como de los procesos de desarrollo local."),
        ("Coherencia con los valores institucionales", "Expresa compromiso con los principios de solidaridad, justicia social, respeto y servicio."),
        ("Comunicación efectiva", "Capacidad de expresión oral y escrita clara, empática y coherente con el enfoque institucional."),
        ("Disponibilidad y compromiso", "Disposición para desplazarse al territorio, cumplimiento de horarios y acompañamiento a procesos comunitarios."),
        ("Adecuación al salario propuesto", "Acepta las condiciones salariales y demuestra motivación no solo económica."),
    ]

    for nombre, descripcion in criterios:
        Criterio.objects.get_or_create(
            idvariable=variable,
            nombrecriterio=nombre,
            defaults={
                "descripcioncriterio": descripcion,
                "estado": True,
                "idusuario": 1
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_remove_aspirante_idestado_postulacion_idestado'),
    ]

    operations = [
        migrations.RunPython(agregar_criterios_entrevista),
    ]
