# Generated by Django 5.2.6 on 2025-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0029_auto_20251102_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='induccion',
            name='fechafin',
        ),
        migrations.RemoveField(
            model_name='inducciondocumento',
            name='idinforme',
        ),
        migrations.AddField(
            model_name='induccion',
            name='nombre',
            field=models.CharField(default='Inducción General', max_length=200),
        ),
    ]
