# Generated by Django 5.2.6 on 2025-11-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_remove_induccion_fechafin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='convocatorias', to='rrhh.estado'),
        ),
    ]
