# Generated by Django 5.2.6 on 2025-11-06 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_capacitacion_idestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.estado'),
        ),
    ]
