# Generated by Django 5.2.6 on 2025-11-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_convocatoria_idestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.estado'),
        ),
        migrations.AddField(
            model_name='evaluacioncriterio',
            name='idpostulacion',
            field=models.ForeignKey(blank=True, db_column='idPostulacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.postulacion'),
        ),
    ]
