# Generated by Django 5.2.6 on 2025-11-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0033_ausencia_idestado_evaluacioncriterio_idpostulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='nombrecriterio',
            field=models.CharField(db_column='nombreCriterio', max_length=500),
        ),
    ]
