#Generated by Django 5.2.6 on 2025-11-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0034_alter_criterio_nombrecriterio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inducciondocumento',
            name='fechacompletado',
        ),
    ]
