# Generated by Django 5.2.6 on 2025-11-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0035_remove_inducciondocumento_fechacompletado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='rrhh.usuario')),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
    ]
