# Generated by Django 5.2.6 on 2025-11-16 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0036_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.usuario'),
        ),
    ]
